version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432'
    networks:
      - my-network
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    image: node:lts
    working_dir: /api
    volumes:
      - ./:/api
    command: sh -c "npm install && npm run start"
    ports:
      - '3000:3000'
    networks:
      - my-network
    depends_on:
      - db

volumes:
  db-data:

networks:
  my-network:
